CREATE TABLE `tcs_veron_cat` (
  `viz_RAJ2000` double,
  `viz_DEJ2000` double,
  `recno` bigint unsigned,
  `Cl` varchar(1),
  `nR` varchar(1),
  `Name` varchar(17),
  `RAJ2000` varchar(10),
  `DEJ2000` varchar(9),
  `n_RAh` varchar(1),
  `F6cm` float,
  `r_F6cm` int,
  `F20cm` float,
  `r_F20cm` int,
  `l_z` varchar(1),
  `z` float,
  `Sp` varchar(4),
  `n_Vmag` varchar(1),
  `Vmag` float,
  `B-V` float,
  `U-B` float,
  `Mabs` float,
  `FC` int,
  `r_Vmag` int,
  `r_z` int,
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
