CREATE TABLE `tcs_2mass_xsc_cat` (
  `designation` varchar(16),
  `ra` double,
  `decl` double,
  `r_k20fe` double,
  `j_m_k20fe` double,
  `j_msig_k20fe` double,
  `j_flg_k20fe` int(11),
  `h_m_k20fe` double,
  `h_msig_k20fe` double,
  `h_flg_k20fe` int(11),
  `k_m_k20fe` double,
  `k_msig_k20fe` double,
  `k_flg_k20fe` int(11),
  `k_ba` double,
  `k_phi` int(11),
  `sup_ba` double,
  `sup_phi` int(11),
  `r_ext` double,
  `j_m_ext` double,
  `j_msig_ext` double,
  `h_m_ext` double,
  `h_msig_ext` double,
  `k_m_ext` double,
  `k_msig_ext` double,
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_designation` (`designation`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_radecl` (`ra`,`decl`)
) ENGINE=MyISAM;
