CREATE TABLE `tcs_cat_deep2dr3` (
  `OBJNO` bigint unsigned NOT NULL,	
  `RA_deg` double NOT NULL,	
  `DEC_deg` double NOT NULL,	
  `MAGB` float,	
  `MAGR` float,	
  `MAGI` float,		
  `PGAL` float,		
  `SFD_EBV` float,	
  `CLASS` varchar(15),	
  `SUBCLASS` varchar(15),
  `OBJNAME` bigint unsigned,	
  `MASKNAME` bigint unsigned,	
  `SLITNAME` bigint unsigned,	
  `DATE`  varchar(15),
  `MJD` float,
  `Z` double,
  `ZHELIO` double,	
  `Z_ERR` double,	
  `RCHI2` float,	
  `DOF` float,
  `VDISP` float,	
  `VDISP_ERR` float,	
  `ZQUALITY` float,	
  `COMMENT` varchar(30),	
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_OBJNO` (`OBJNO`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_RA_deg_DEC_deg` (`RA_deg`,`DEC_deg`)
) ENGINE=MyISAM;
