CREATE TABLE `tcs_cat_md02_giacconi2002` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `viz_ID` bigint unsigned,
  `[GZW2002]` bigint unsigned,
  `Name` varchar(30),
  `RAJ2000` varchar(15),
  `DEJ2000` varchar(15),
  `SCts` float,
  `e_SCts` float,
  `HCts` float,
  `e_HCts` float,
  `STime` float,
  `HTime` float,
  `l_SFlux` varchar(1),
  `SFlux` float,
  `e_SFlux` float,
  `l_HFlux` varchar(1),
  `HFlux` float,
  `e_HFlux` float,
  `HR` float,
  `e_HR` float,
  `PosErr` float,
  `Sep` float,
  `l_Rmag` varchar(1),
  `Rmag` float,
  `e_Rmag` float,
  `f_Rmag` varchar(1),
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
