CREATE TABLE `tcs_cat_md04_trump2007` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `[TIM2007]` varchar(30),
  `RAJ2000` double,
  `DEJ2000` double,
  `imag` float,
  `S_to_N` float,
  `Texp` bigint unsigned,
  `Type` varchar(5),
  `z` float,
  `n_z` varchar(3),
  `e_z` float,
  `n_e_z` varchar(3),
  `zconf` varchar(5),
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
