CREATE TABLE `tcs_cat_md02_lehmer2005` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `n_[LBA2005]` varchar(1),
  `[LBA2005]` varchar(5),
  `RAJ2000` varchar(15),
  `DEJ2000` varchar(15),
  `e_pos` float,
  `OffAxis` float,
  `FCts` float,	
  `uperr_FCts` float, 
  `lowerr_FCts` float,
  `SCts` float, 	
  `uperr_SCts` float,
  `lowerr_SCts` float,
  `HCts` float,	
  `uperr_HCts` float, 
  `lowerr_HCts` float,
  `RAO` varchar(15),	
  `DEO` varchar(15),	
  `O-XOff` float,
  `Rcmag` float, 
  `[ABB2003]`  bigint unsigned, 
  `RAA` varchar(15),	
  `DEA` varchar(15),	
  `[GZW2002]` bigint unsigned,
  `RAG` varchar(15), 	
  `DEG` varchar(15), 	
  `FTime` float, 
  `STime` float, 
  `HTime` float,
  `H/S` float, 	
  `uperr_H/S` float, 
  `lowerr_H/S` float, 
  `Gamma` float, 
  `l_Gamma` varchar(1), 
  `uperr_Gamma` float,  
  `lowerr_Gamma` float,  
  `FFlux` double,  
  `SFlux` double,  
  `HFlux` double,  
  `Field`  bigint unsigned,
  `Log(P)` float, 
  `Notes` varchar(5), 
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
