CREATE TABLE tcs_2mass_psc_cat (
    ra double,
    decl double,
    err_maj float,
    err_min float,
    err_ang smallint,
    designation varchar(17),
    j_m float,
    j_cmsig float,
    j_msigcom float,
    j_snr float,
    h_m float,
    h_cmsig float,
    h_msigcom float,
    h_snr float,
    k_m float,
    k_cmsig float,
    k_msigcom float,
    k_snr float,
    ph_qual varchar(3),
    rd_flg varchar(3),
    bl_flg varchar(3),
    cc_flg varchar(3),
    ndet varchar(6),
    prox float,
    pxpa smallint,
    pxcntr int,
    gal_contam smallint,
    mp_flg smallint,
    pts_key int,
    hemis varchar(1),
    date date,
    scan smallint,
    glon float,
    glat float,
    x_scan float,
    jdate double,
    j_psfchi float,
    h_psfchi float,
    k_psfchi float,
    j_m_stdap float,
    j_msig_stdap float,
    h_m_stdap float,
    h_msig_stdap float,
    k_m_stdap float,
    k_msig_stdap float,
    dist_edge_ns int,
    dist_edge_ew int,
    dist_edge_flg varchar(2),
    dup_src smallint,
    use_src smallint,
    a varchar(1),
    dist_opt float,
    phi_opt smallint,
    b_m_opt float,
    vr_m_opt float,
    nopt_mchs smallint,
    ext_key int,
    scan_key int,
    coadd_key int,
    coadd smallint,
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_designation` (`designation`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_radecl` (`ra`,`decl`)
) ENGINE=MyISAM;

