drop table if exists `tcs_cat_milliquas`;

create table `tcs_cat_milliquas` (
`id` char(15),
`ra` char(12),
`decl` char(12),
`name` varchar(26),
`descrip` char(4),
`rmag` float,
`bmag` float,
`comment` char(2),
`r_psf_class` char(3),
`b_psf_class` char(2),
`z` float,
`src_cat_name` char(3),
`src_cat_z` char(3),
`qso_prob` float,
`r_name` varchar(22),
`x_name` varchar(22),
`ra_deg` double,
`dec_deg` double,
`htm20ID` bigint(20) unsigned,
`htm16ID` bigint(20) unsigned,
`cx` double,
`cy` double,
`cz` double,
PRIMARY KEY `idx_id` (`id`),
KEY `idx_htm20ID` (`htm20ID`),
KEY `idx_htm16ID` (`htm16ID`),
KEY `idx_ra_deg_dec_deg` (`ra_deg`,`dec_deg`)
) ENGINE=MyISAM;
