create table `tcs_cat_sdss_stars_galaxies` (
`Objid` bigint NOT NULL,
`ra` double NOT NULL,
`dec_` double NOT NULL,
`mode` tinyint,
`type` smallint,
`specObjID` bigint,
`petroMag_u` float,
`petroMag_g` float,
`petroMag_r` float,
`petroMag_i` float,
`petroMag_z` float,
`extinction_u` float,
`extinction_g` float,
`extinction_r` float,
`extinction_i` float,
`extinction_z` float,
`petroMagErr_u` float,
`petroMagErr_g` float,
`petroMagErr_r` float,
`petroMagErr_i` float,
`petroMagErr_z` float,
`z_` float,
`zErr` float,
`dmod` float,
`rest_ug` float,
`rest_gr` float,
`rest_ri` float,
`rest_iz` float,
`absMag_u` float,
`absMag_g` float,
`absMag_r` float,
`absMag_i` float,
`absMag_z` float,
`u` float,
`g` float,
`r` float,
`i` float,
`z` float,
`Err_u` float,
`Err_g` float,
`Err_r` float,
`Err_i` float,
`Err_z` float,
`psfMag_u` float,
`psfMag_g` float,
`psfMag_r` float,
`psfMag_i` float,
`psfMag_z` float,
`psfMagErr_u` float,
`psfMagErr_g` float,
`psfMagErr_r` float,
`psfMagErr_i` float,
`psfMagErr_z` float,
`htm20ID` bigint(20) unsigned,
`htm16ID` bigint(20) unsigned,
`cx` double,
`cy` double,
`cz` double,
KEY `key_ObjID` (`ObjID`),
KEY `idx_htm20ID` (`htm20ID`),
KEY `idx_htm16ID` (`htm16ID`),
KEY `idx_radec` (`ra`,`dec_`)
) ENGINE=MyISAM;

