create table `tcs_cat_sdss_dr9_spect_galaxies_qsos` (
`objID` bigint NOT NULL,
`ra` double NOT NULL,
`dec_` double NOT NULL,
`raErr` double,
`decErr` double,
`obj` smallint,
`mode` tinyint,
`nChild` smallint,
`type` smallint NOT NULL,
`clean` int,
`probPSF` float,
`insideMask` tinyint,
`flags` bigint,
`psfMag_u` float,
`psfMag_g` float,
`psfMag_r` float,
`psfMag_i` float,
`psfMag_z` float,
`psfMagErr_u` float,
`psfMagErr_g` float,
`psfMagErr_r` float,
`psfMagErr_i` float,
`psfMagErr_z` float,
`petroMag_u` float,
`petroMag_g` float,
`petroMag_r` float,
`petroMag_i` float,
`petroMag_z` float,
`petroMagErr_u` float,
`petroMagErr_g` float,
`petroMagErr_r` float,
`petroMagErr_i` float,
`petroMagErr_z` float,
`probPSF_u` float,
`probPSF_g` float,
`probPSF_r` float,
`probPSF_i` float,
`probPSF_z` float,
`extinction_u` float,
`extinction_g` float,
`extinction_r` float,
`extinction_i` float,
`extinction_z` float,
`mjd` int,
`loadVersion` int,
`parentID` bigint,
`specObjID` bigint,
`u` float,
`g` float,
`r` float,
`i` float,
`z` float,
`err_u` float,
`err_g` float,
`err_r` float,
`err_i` float,
`err_z` float,
`nObserve` int,
`nDetect` int,
`nEdge` int,
`score` float,
`TAI_u` double,
`TAI_g` double,
`TAI_r` double,
`TAI_i` double,
`TAI_z` double,
`z_` float,
`zErr` float,
`objType` char(3), -- 'G' = Galaxy, 'Q' = QSO
`htm20ID` bigint(20) unsigned NOT NULL,
`htm16ID` bigint(20) unsigned NOT NULL,
`cx` double NOT NULL,
`cy` double NOT NULL,
`cz` double NOT NULL,
KEY `key_ObjID` (`ObjID`),
KEY `idx_htm20ID` (`htm20ID`),
KEY `idx_htm16ID` (`htm16ID`),
KEY `idx_radec` (`ra`,`dec_`),
KEY `idx_type` (`type`),
KEY `idx_objType` (`objType`)
) ENGINE=MyISAM;

