CREATE TABLE `tcs_cat_md04_hasinger2007` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `XMMC`  bigint unsigned,
  `Xpos` float,
  `Ypos` float,
  `RAJ2000` double,
  `DEJ2000` double,
  `ePos` float,
  `FX(0.5-2)` float,
  `e_FX(0.5-2)` float,
  `CS` float,
  `e_CS` float,
  `CRS` float,
  `e_CRS` float,
  `DETS` double,
  `bgS`  float,
  `ExpmapS` float,
  `FX(2-10)` float,
  `e_FX(2-10)` float,
  `CM` float,
  `e_CM` float,
  `CRM` float,
  `e_CRM` float,
  `DETM` double,
  `bgM` float,
  `ExpmapM` double,
  `FX(5-10)` float,
  `e_FX(5-10)` float,
  `CH` float,
  `e_CH` float,  
  `CRH` float,
  `e_CRH` float,
  `DETH` double,
  `bgH` float,
  `ExpmapH` double,
  `HR` float,
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
