CREATE TABLE `tcs_cat_md07_nandra2005` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `Seq`	varchar(5),	
  `Field` varchar(5),	
  `CXO` varchar(15),	
  `l_FB` varchar(1),		
  `FB` float,	
  `uperr_FB` float,		
  `lowerr_FB` float,		
  `l_SB` varchar(1),		
  `SB` float,		
  `uperr_SB` float,		
  `lowerr_SB` float,		
  `l_HB` varchar(1),		
  `HB` float,		
  `uperr_HB` float,		
  `lowerr_HB` float,		
  `l_UB` varchar(1),		
  `UB` float,		
  `uperr_UB` float,		
  `lowerr_UB` float,		
  `l_F0.5-10keV` varchar(1),	
  `F0.5-10keV` float,	
  `uperr_F0.5-10keV` float,	
  `lowerr_F0.5-10keV` float,	
  `l_F0.5-2keV` varchar(1),
  `F0.5-2keV` float,	
  `uperr_F0.5-2keV` float,	
  `lowerr_F0.5-2keV` float,	
  `l_F2-10keV` varchar(1),
  `F2-10keV` float,	
  `uperr_F2-10keV` float,	
  `lowerr_F2-10keV` float,	
  `l_F5-10keV` varchar(1),
  `F5-10keV` float,	
  `uperr_F5-10keV` float,	
  `lowerr_F5-10keV` float,	
  `log(Pmin)` float,	
  `OAA` float,		
  `HR` float,		
  `Flags` varchar(7),	
  `_RA`	double,	
  `_DE`	double,	
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
