CREATE TABLE `tcs_cat_md05_brunner2008` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `XMMNR` bigint unsigned,
  `ROSNR` bigint unsigned,	
  `ClR` varchar(10),
  `ClX` varchar(10),
  `XMMU` varchar(30),
  `e_Pos` float,	
  `Ldet0` bigint unsigned,
  `CR0` float,
  `e_CR0` float,	
  `Flux0` float,	
  `e_Flux0` float,	
  `Ldet1` bigint unsigned,	
  `CR1` float,
  `e_CR1` float,	
  `Flux1` float,	
  `e_Flux1` float,	
  `Ldet2` bigint unsigned,	
  `CR2` float,
  `e_CR2` float,	
  `Flux2` float,	
  `e_Flux2` float,	
  `Ldet3` bigint unsigned,	
  `CR3` float,
  `e_CR3` float,	
  `Flux3` float,	
  `e_Flux3` float,	
  `HR1` float,
  `e_HR1` float,	
  `HR2` float,
  `e_HR2` float,	
  `HR3` float,
  `e_HR3` float,	
  `RAJ2000` varchar(15),	
  `DEJ2000` varchar(15),	
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
