CREATE TABLE `tcs_cat_md07_laird2009` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `egs` bigint unsigned,		
  `Field` varchar(30),	
  `CXOEGS` varchar(30),	
  `lowerr_Pos` float,	
  `OAA`	 float,	
  `Fcts` bigint unsigned,		
  `Fbkg` float,		
  `Scts` bigint unsigned,		
  `Sbkg` float,		
  `Hcts` bigint unsigned,		
  `Hbkg` float,	
  `Ucts` bigint unsigned,		
  `Ubkg` float,		
  `Band` varchar(7),		
  `badProb` float,	
  `n_egs` varchar(7),	
  `l_FBay` varchar(1),	
  `FBay` float,		
  `uperr_FBay` float,	
  `lowerr_FBay` float,	
  `l_SBay` varchar(1),	
  `SBay` float,		
  `uperr_SBay` float,	
  `lowerr_SBay` float,	
  `l_HBay` varchar(1),	
  `HBay` float,		
  `uperr_HBay` float,	
  `lowerr_HBay` float,	
  `l_UBay` varchar(1),	
  `UBay` float,		
  `uperr_UBay` float,	
  `lowerr_UBay` float,	
  `l_Fclas` varchar(1),	
  `Fclas` float,	
  `uperr_Fclas` float,	
  `lowerr_Fclas` float,	
  `l_Sclas` varchar(1),	
  `Sclas` float,	
  `uperr_Sclas` float,	
  `lowerr_Sclas` float,	
  `l_Hclas` varchar(1),	
  `Hclas` float,	
  `uperr_Hclas` float,	
  `lowerr_Hclas` float,	
  `l_Uclas` varchar(1),	
  `Uclas` float,	
  `uperr_Uclas` float,	
  `lowerr_Uclas` float,	
  `HRb`	 float,	
  `uperr_HRb` float,	
  `lowerr_HRb` float,	
  `HRc` float,		
  `Q` bigint unsigned,		
  `f_egs` varchar(7),	
  `l_Rmag` varchar(1),	
  `Rmag` float,		
  `DEEP2-X` float,	
  `LR-DEEP2` float,	
  `DEEP2-ID` bigint unsigned,	
  `l_imag` varchar(1),	
  `imag` float,	
  `CFHT-X` float,	
  `LR-CFHT` float,	
  `CFHT-ID` varchar(15),	
  `l_3.6mag` varchar(1),	
  `3.6mag` float,	
  `IRAC-X` float,
  `LR-IRAC` float,	
  `EGSIRAC` varchar(15),		
  `RAJ2000` double,	
  `DEJ2000` double,
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
