CREATE TABLE `tcs_cat_md01_pierre2007` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `XSeq` bigint unsigned,
  `XLSS` varchar(17),
  `RAJ2000` varchar(10),
  `DEJ2000` varchar(12),
  `BSeq` bigint unsigned,
  `XLSSB` varchar(20),
  `Bc1c2` bigint unsigned,
  `Bcorerad` float,
  `Bextlike` float,
  `Bdetlike` float,
  `Boffaxis` float,
  `BRA` varchar(10),
  `BDE` varchar(11),
  `eBpos` float,
  `Bratemos` float,
  `Bratepn` float,
  `Bflux` float,
  `f_Bflux` bigint unsigned,
  `CDSeq` bigint unsigned,
  `XLSSCD` varchar(17),
  `CDcorerad` float,
  `CDextlike` float,
  `CDdetlike` float,
  `CDoffaxis` float,
  `CDRA` varchar(10),
  `CDDE` varchar(11),
  `eCDpos` float,
  `CDratemos` float,
  `CDratepn` float,
  `CDflux` float,
  `f_CDflux` bigint unsigned,
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
