CREATE TABLE `tcs_cat_md02_virani2006` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `[VTU2006]` bigint unsigned,	
  `CXOYECDF` varchar(30),	
  `n_CXOYECDF` bigint unsigned,	
  `RAJ2000` varchar(15),	
  `DEJ2000` varchar(15),	
  `PSF` float,
  `CRf` float,
  `uperr_CRf` float,
  `lowerr_CRf` float,	
  `CRs` float,
  `uperr_CRs` float,	
  `lowerr_CRs` float,	
  `CRh` float,
  `uperr_CRh` float,
  `lowerr_CRh` float,	
  `Ffull` float,	
  `Fsoft` float,	
  `Fhard` float,	
  `Notes` varchar(15),	
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
