CREATE TABLE `tcs_cat_md01_chiappetti2005` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `Seq` bigint unsigned,
  `XMDS` varchar(16),
  `RAJ2000` varchar(10),
  `DEJ2000` varchar(11),
  `CountB` float,
  `e_CountB` float,
  `CountCD` float,
  `e_CountCD` float,
  `FluxB` float,  
  `FluxCD` float,  
  `bBand` varchar(2),
  `Gap` int,
  `Rank` int,
  `DistXO` float,
  `Rmag` float,
  `e_Rmag` float,
  `Imag` float,
  `e_Imag` float,
  `Opt` int,
  `VR` varchar(1),
  `LR` varchar(1),
  `CatName` varchar(40),
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
