CREATE TABLE `tcs_cat_md02_lefevre2004` (
  `viz_RAJ2000` double NOT NULL,
  `viz_DEJ2000` double NOT NULL,
  `recno` bigint unsigned NOT NULL,
  `HST-GOODS` varchar(30),
  `VCDFS` bigint unsigned,
  `RAJ2000` double,
  `DEJ2000` double,
  `z` float,
  `f_z` bigint unsigned,
  `Imag` float,
  `VVDS` varchar(5),
  `Link` varchar(5),
  `htm20ID` bigint(20) unsigned,
  `htm16ID` bigint(20) unsigned,
  `cx` double,
  `cy` double,
  `cz` double,
  `id` bigint(20) unsigned,
  KEY `key_id` (`id`),
  KEY `key_recno` (`recno`),
  KEY `idx_htm20ID` (`htm20ID`),
  KEY `idx_htm16ID` (`htm16ID`),
  KEY `idx_viz_raj2000_viz_dej2000` (`viz_RAJ2000`,`viz_DEJ2000`)
) ENGINE=MyISAM;
