create table `tcs_sdss_stars_cat` (
`Objid` bigint NOT NULL,
`ra` double NOT NULL,
`dec_` double NOT NULL,
`mode` tinyint,
`type` smallint,
`specObjID` bigint,
`petroMag_u` float,
`petroMag_g` float,
`petroMag_r` float,
`petroMag_i` float,
`petroMag_z` float,
`extinction_u` float,
`extinction_g` float,
`extinction_r` float,
`extinction_i` float,
`extinction_z` float,
`petroMagErr_u` float,
`petroMagErr_g` float,
`petroMagErr_r` float,
`petroMagErr_i` float,
`petroMagErr_z` float,
`htm20ID` bigint(20) unsigned,
`htm16ID` bigint(20) unsigned,
`cx` double,
`cy` double,
`cz` double,
KEY `key_ObjID` (`ObjID`),
KEY `idx_htm20ID` (`htm20ID`),
KEY `idx_htm16ID` (`htm16ID`),
KEY `idx_radec` (`ra`,`dec_`)
) ENGINE=MyISAM;
